#!/bin/bash
export FZF_DEFAULT_OPTS="
	--color=fg:#908caa \
  --color=bg:#191724 \
  --color=hl:#ebbcba \
	--color=fg+:#e0def4 \
  --color=bg+:#26233a \
  --color=hl+:#ebbcba \
	--color=border:#403d52 \
  --color=header:#31748f \
  --color=gutter:#191724
	--color=spinner:#f6c177 \
  --color=info:#9ccfd8 \
	--color=pointer:#c4a7e7 \
  --color=marker:#eb6f92 \
  --color=prompt:#908caa"
