# == LAZYGIT =====================================
# --- THEME --------------------------------------
# See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
gui:
  nerdFontsVersion: "3" # Show NerdFont icons v3. Blank for no icons
  theme:
    # Border color of focused window
    activeBorderColor:
      - magenta
      - bold
    # Border color of non-focused windows
    inactiveBorderColor:
      - '#6e6a86' # fg2
    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - '#26233a' # bg2
